import { LeaderboardEntry } from "../types";

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "1",
    displayName: "Sarah M.",
    score: 12500,
    streak: 45,
    isCurrentUser: false,
  },
  {
    rank: 2,
    userId: "2",
    displayName: "Max K.",
    score: 11200,
    streak: 32,
    isCurrentUser: false,
  },
  {
    rank: 3,
    userId: "3",
    displayName: "Lisa B.",
    score: 10800,
    streak: 28,
    isCurrentUser: false,
  },
  {
    rank: 4,
    userId: "4",
    displayName: "Tom H.",
    score: 9500,
    streak: 21,
    isCurrentUser: false,
  },
  {
    rank: 5,
    userId: "5",
    displayName: "Anna W.",
    score: 8900,
    streak: 19,
    isCurrentUser: false,
  },
  {
    rank: 6,
    userId: "6",
    displayName: "Felix S.",
    score: 8200,
    streak: 15,
    isCurrentUser: false,
  },
  {
    rank: 7,
    userId: "7",
    displayName: "Julia R.",
    score: 7800,
    streak: 12,
    isCurrentUser: false,
  },
  {
    rank: 8,
    userId: "8",
    displayName: "David L.",
    score: 7200,
    streak: 10,
    isCurrentUser: false,
  },
  {
    rank: 9,
    userId: "9",
    displayName: "Nina K.",
    score: 6500,
    streak: 8,
    isCurrentUser: false,
  },
  {
    rank: 10,
    userId: "10",
    displayName: "Paul M.",
    score: 5800,
    streak: 5,
    isCurrentUser: false,
  },
  {
    rank: 42,
    userId: "current",
    displayName: "Du",
    score: 3200,
    streak: 7,
    isCurrentUser: true,
  },
];
